fork = false
frame = "full"
idle = true
maximized = true
neovim-bin = "/home/simon/opt/nvim-linux-x86_64/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal = ["FiraCode Nerd Font Mono"] # Will use the bundled Fira Code Nerd Font by default
size = 8
